import { lessons, type Lesson, type PhraseItem, type VocabItem } from "./lessons";

export type CEFR = "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
export type CurriculumLesson = Lesson & {
  cefr: CEFR;
  unit: string;
  skill: string;
  order: number;
  core?: boolean;
};

export const levels: Array<{id:CEFR;name:string;arabic:string;summary:string;arabicSummary:string;tone:string}> = [
  {id:"A1",name:"Breakthrough",arabic:"البداية",summary:"Understand and use essential everyday Arabic.",arabicSummary:"افهم واستخدم العربية الأساسية في الحياة اليومية.",tone:"Start"},
  {id:"A2",name:"Elementary",arabic:"الأساسيات",summary:"Handle familiar situations with more independence.",arabicSummary:"تصرّف بثقة أكبر في المواقف المألوفة.",tone:"Build"},
  {id:"B1",name:"Intermediate",arabic:"المتوسط",summary:"Speak about life, work, travel, and opinions.",arabicSummary:"تحدث عن الحياة والعمل والسفر والآراء.",tone:"Communicate"},
  {id:"B2",name:"Upper-intermediate",arabic:"فوق المتوسط",summary:"Discuss complex topics with clearer nuance.",arabicSummary:"ناقش الموضوعات المعقدة بوضوح ودقة أكبر.",tone:"Express"},
  {id:"C1",name:"Advanced",arabic:"المتقدم",summary:"Use precise language in academic and professional settings.",arabicSummary:"استخدم لغة دقيقة في السياقات الأكاديمية والمهنية.",tone:"Master"},
  {id:"C2",name:"Proficiency",arabic:"الإتقان",summary:"Control register, nuance, style, and sophisticated expression.",arabicSummary:"تحكم في الأسلوب والدقة والفروق الدقيقة والتعبير المتقدم.",tone:"Polish"},
];

const levelBand = (cefr:CEFR): Lesson["levelEn"] => cefr === "A1" ? "beginner" : cefr === "A2" || cefr === "B1" || cefr === "B2" ? "intermediate" : "advanced";
const levelAr = (cefr:CEFR): Lesson["level"] => cefr === "A1" ? "مبتدئ" : cefr === "A2" || cefr === "B1" || cefr === "B2" ? "متوسط" : "متقدم";

const extra = (cfg:{id:string;title:string;arabicTitle:string;cefr:CEFR;unit:string;skill:string;icon:string;category:string;description:string;words:Array<[string,string,string]>;phrases:Array<[string,string,string]>;tip?:string}):CurriculumLesson => {
  const vocabulary:VocabItem[] = cfg.words.map(([arabic,translit,meaning])=>({arabic,translit,meaning}));
  const phrases:PhraseItem[] = cfg.phrases.map(([arabic,translit,meaning])=>({arabic,translit,meaning}));
  const options = (index:number) => {
    const pool = vocabulary.map(v=>v.meaning);
    return [vocabulary[index % vocabulary.length].meaning, pool[(index+1)%pool.length], pool[(index+2)%pool.length], pool[(index+3)%pool.length]];
  };
  const quiz = [0,1,2,3].map((i)=>({question:`What does «${vocabulary[i].arabic}» mean?`,options:options(i),answerIndex:0,explanation:`${vocabulary[i].arabic} — ${vocabulary[i].meaning}.`}));
  return {id:cfg.id,title:cfg.title,arabicTitle:cfg.arabicTitle,cefr:cfg.cefr,unit:cfg.unit,skill:cfg.skill,order:0,icon:cfg.icon,category:cfg.category,description:cfg.description,level:levelAr(cfg.cefr),levelEn:levelBand(cfg.cefr),accent:cfg.cefr === "A1" || cfg.cefr === "A2" ? "sage" : cfg.cefr === "B1" || cfg.cefr === "B2" ? "clay" : "gold",duration:"10 دقائق",durationEn:10,vocabulary,phrases,quiz,tip:cfg.tip};
};

const coreLevels:Record<string,CEFR>={greetings:"A1",numbers:"A1",family:"A1",food:"A1",time:"A2",verbs:"A2",travel:"A2",shopping:"A2",conversation:"B1"};
const coreUnits:Record<string,string>={greetings:"Foundations",numbers:"Foundations",family:"Everyday life",food:"Everyday life",time:"Everyday life",verbs:"Action & grammar",travel:"Real-world Arabic",shopping:"Real-world Arabic",conversation:"Real-world Arabic"};
const coreSkills:Record<string,string>={greetings:"Speaking",numbers:"Functional language",family:"Speaking",food:"Functional language",time:"Listening",verbs:"Grammar",travel:"Survival Arabic",shopping:"Survival Arabic",conversation:"Conversation"};
const core:CurriculumLesson[] = lessons.map((lesson,idx)=>({...lesson,cefr:coreLevels[lesson.id] ?? "A1",unit:coreUnits[lesson.id] ?? "Core course",skill:coreSkills[lesson.id] ?? "Core skill",order:idx+1,core:true}));

export const supplementalLessons:CurriculumLesson[] = [
  extra({id:"a1-self-introduction",title:"Introduce Yourself",arabicTitle:"التعريف بالنفس",cefr:"A1",unit:"Foundations",skill:"Speaking",icon:"🙋",category:"Foundations",description:"Say who you are, where you are from, and what you do in simple Arabic.",words:[["أنا","Anā","I / me"],["أنت","Anta / anti","You"],["اسمي","Ismī","My name is"],["من","Min","From"],["طالب","Ṭālib","Student"],["عمل","ʿAmal","Work / job"]],phrases:[["أنا من مصر","Anā min Miṣr","I am from Egypt"],["أنا طالب","Anā ṭālib","I am a student"],["ما عملك؟","Mā ʿamaluk?","What is your job?"]]}),
  extra({id:"a1-people-pronouns",title:"People & Pronouns",arabicTitle:"الأشخاص والضمائر",cefr:"A1",unit:"Foundations",skill:"Grammar",icon:"👥",category:"Foundations",description:"Recognize the most useful personal pronouns and simple descriptions.",words:[["هو","Huwa","He"],["هي","Hiya","She"],["نحن","Naḥnu","We"],["هم","Hum","They"],["صديق","Ṣadīq","Friend"],["مدرس","Mudarris","Teacher"]],phrases:[["هو صديقي","Huwa ṣadīqī","He is my friend"],["هي معلمة","Hiya muʿallima","She is a teacher"],["نحن هنا","Naḥnu hunā","We are here"]]}),
  extra({id:"a1-home-basics",title:"Home Basics",arabicTitle:"أساسيات المنزل",cefr:"A1",unit:"Everyday life",skill:"Vocabulary",icon:"🏠",category:"Everyday life",description:"Learn the everyday words you need to describe a simple home.",words:[["بيت","Bayt","House / home"],["غرفة","Ghurfa","Room"],["باب","Bāb","Door"],["نافذة","Nāfidha","Window"],["مطبخ","Maṭbakh","Kitchen"],["حمام","Ḥammām","Bathroom"]],phrases:[["هذا بيتي","Hādhā baytī","This is my home"],["أين المطبخ؟","Ayna al-maṭbakh?","Where is the kitchen?"],["افتح الباب","Iftaḥ al-bāb","Open the door"]]}),
  extra({id:"a1-food-basics",title:"Food & Drinks",arabicTitle:"الطعام والشراب",cefr:"A1",unit:"Everyday life",skill:"Survival Arabic",icon:"🍽️",category:"Everyday life",description:"Order simple food and drinks and say what you want.",words:[["ماء","Māʾ","Water"],["خبز","Khubz","Bread"],["قهوة","Qahwa","Coffee"],["شاي","Shāy","Tea"],["أرز","Aruz","Rice"],["دجاج","Dajā?","Chicken"]],phrases:[["أريد ماءً","Urīdu māʾan","I want water"],["من فضلك، قهوة","Min faḍlik, qahwa","Coffee, please"],["أنا جائع","Anā jāʾiʿ","I am hungry"]]}),
  extra({id:"a2-daily-routine",title:"Daily Routine",arabicTitle:"الروتين اليومي",cefr:"A2",unit:"Everyday life",skill:"Speaking",icon:"🌅",category:"Everyday life",description:"Talk about your routine using common present-tense verbs.",words:[["أستيقظ","Astayqiẓ","I wake up"],["أذهب","Adhhab","I go"],["أدرس","Adrusu","I study"],["أعمل","Aʿmal","I work"],["أعود","Aʿūd","I return"],["أنام","Anām","I sleep"]],phrases:[["أستيقظ مبكراً","Astayqiẓ mubakkiran","I wake up early"],["أذهب إلى العمل","Adhhab ilā al-ʿamal","I go to work"],["أعود مساءً","Aʿūd masāʾan","I return in the evening"]]}),
  extra({id:"a2-time-dates",title:"Time, Days & Dates",arabicTitle:"الوقت والأيام والتواريخ",cefr:"A2",unit:"Everyday life",skill:"Listening",icon:"🗓️",category:"Everyday life",description:"Ask for times, days, dates, and simple appointments.",words:[["اليوم","Al-yawm","Today"],["غداً","Ghadan","Tomorrow"],["أمس","Ams","Yesterday"],["الساعة","As-sāʿa","The hour / time"],["الاثنين","Al-ithnayn","Monday"],["موعد","Mawʿid","Appointment"]],phrases:[["كم الساعة؟","Kam as-sāʿa?","What time is it?"],["موعدي غداً","Mawʿidī ghadan","My appointment is tomorrow"],["نلتقي يوم الاثنين","Naltaqī yawm al-ithnayn","We meet on Monday"]]}),
  extra({id:"a2-weather",title:"Weather & Seasons",arabicTitle:"الطقس والفصول",cefr:"A2",unit:"Everyday life",skill:"Conversation",icon:"☀️",category:"Everyday life",description:"Describe weather conditions and make simple plans around them.",words:[["طقس","Ṭaqs","Weather"],["حار","Ḥārr","Hot"],["بارد","Bārid","Cold"],["مطر","Maṭar","Rain"],["شمس","Shams","Sun"],["شتاء","Shitāʾ","Winter"]],phrases:[["الطقس جميل","Aṭ-ṭaqs jamīl","The weather is nice"],["الجو بارد اليوم","Al-jaww bārid al-yawm","It is cold today"],["هل ستمطر؟","Hal satumṭir?","Will it rain?"]]}),
  extra({id:"a2-directions",title:"Directions & Places",arabicTitle:"الاتجاهات والأماكن",cefr:"A2",unit:"Real-world Arabic",skill:"Survival Arabic",icon:"🧭",category:"Real-world",description:"Ask where places are and understand basic directions.",words:[["يمين","Yamīn","Right"],["يسار","Yasār","Left"],["أمام","Amām","In front"],["خلف","Khalf","Behind"],["قريب","Qarīb","Near"],["بعيد","Baʿīd","Far"]],phrases:[["أين المحطة؟","Ayna al-maḥaṭṭa?","Where is the station?"],["على اليمين","ʿAlā al-yamīn","On the right"],["هل هو قريب؟","Hal huwa qarīb?","Is it near?"]]}),
  extra({id:"a2-transport",title:"Getting Around",arabicTitle:"التنقل والمواصلات",cefr:"A2",unit:"Real-world Arabic",skill:"Survival Arabic",icon:"🚌",category:"Real-world",description:"Use Arabic for taxis, buses, trains, and simple travel questions.",words:[["حافلة","Ḥāfila","Bus"],["قطار","Qiṭār","Train"],["سيارة","Sayyāra","Car"],["مطار","Maṭār","Airport"],["تذكرة","Tadhkira","Ticket"],["محطة","Maḥaṭṭa","Station"]],phrases:[["أريد تذكرة","Urīdu tadhkira","I want a ticket"],["إلى أين يذهب القطار؟","Ilā ayna yadhhab al-qiṭār?","Where does the train go?"],["خذني إلى المطار","Khudhnī ilā al-maṭār","Take me to the airport"]]}),
  extra({id:"b1-study-work",title:"Study & Work",arabicTitle:"الدراسة والعمل",cefr:"B1",unit:"Study & work",skill:"Speaking",icon:"💼",category:"Study & work",description:"Discuss school, work, schedules, responsibilities, and goals.",words:[["جامعة","Jāmiʿa","University"],["وظيفة","Waẓīfa","Job"],["مشروع","Mashrūʿ","Project"],["اجتماع","Ijtimāʿ","Meeting"],["خبرة","Khibra","Experience"],["هدف","Hadaf","Goal"]],phrases:[["أدرس في الجامعة","Adrusu fī al-jāmiʿa","I study at university"],["لدي خبرة في...","Ladayya khibra fī...","I have experience in..."],["هدفي هو أن أتطور","Hadafī huwa an ataṭawwar","My goal is to improve"]]}),
  extra({id:"b1-health",title:"Health & Well-being",arabicTitle:"الصحة والعافية",cefr:"B1",unit:"Everyday life",skill:"Functional language",icon:"🩺",category:"Everyday life",description:"Explain common symptoms, needs, and practical health situations.",words:[["صحة","Ṣiḥḥa","Health"],["طبيب","Ṭabīb","Doctor"],["دواء","Dawāʾ","Medicine"],["ألم","Alam","Pain"],["حمى","Ḥummā","Fever"],["راحة","Rāḥa","Rest"]],phrases:[["أشعر بالتعب","Ashʿur bi-t-taʿab","I feel tired"],["أحتاج إلى طبيب","Aḥtāju ilā ṭabīb","I need a doctor"],["أين الصيدلية؟","Ayna aṣ-ṣaydaliyya?","Where is the pharmacy?"]]}),
  extra({id:"b1-opinions",title:"Opinions & Reasons",arabicTitle:"الآراء والأسباب",cefr:"B1",unit:"Conversation",skill:"Speaking",icon:"🗣️",category:"Conversation",description:"Give an opinion, agree, disagree, and explain a simple reason.",words:[["رأي","Raʾy","Opinion"],["أعتقد","Aʿtaqid","I think"],["أفضل","Ufaḍḍil","I prefer"],["لأن","Liʾanna","Because"],["لكن","Lākin","But"],["صحيح","Ṣaḥīḥ","Correct / true"]],phrases:[["أعتقد أن...","Aʿtaqid anna...","I think that..."],["أوافقك الرأي","Uwāfiquka ar-raʾy","I agree with you"],["لا أوافق لأن...","Lā uwāfiq liʾanna...","I disagree because..."]]}),
  extra({id:"b1-social-life",title:"Friends & Social Life",arabicTitle:"الأصدقاء والحياة الاجتماعية",cefr:"B1",unit:"Conversation",skill:"Conversation",icon:"☕",category:"Conversation",description:"Keep a natural conversation going beyond greetings and small talk.",words:[["دعوة","Daʿwa","Invitation"],["زيارة","Ziyāra","Visit"],["مناسبة","Munāsaba","Occasion"],["صداقة","Ṣadāqa","Friendship"],["لقاء","Liqāʾ","Meeting"],["ضيوف","Ḍuyūf","Guests"]],phrases:[["هل تريد أن تأتي؟","Hal turīd an taʾtī?","Would you like to come?"],["سعدت بلقائك","Saʿidtu biliqāʾik","I was happy to meet you"],["أراك لاحقاً","Arāka lāḥiqan","See you later"]]}),
  extra({id:"b2-media",title:"News & Media",arabicTitle:"الأخبار والإعلام",cefr:"B2",unit:"Ideas & society",skill:"Reading",icon:"📰",category:"Ideas & society",description:"Follow common media language and summarize what you read or hear.",words:[["خبر","Khabar","News item"],["تقرير","Taqrīr","Report"],["مصدر","Maṣdar","Source"],["حدث","Ḥadath","Event"],["معلومات","Maʿlūmāt","Information"],["تغطية","Taghṭiya","Coverage"]],phrases:[["بحسب التقرير","Bi-ḥasabi at-taqrīr","According to the report"],["المصدر الرئيسي هو...","Al-maṣdar ar-raʾīsī huwa...","The main source is..."],["باختصار، يقول الخبر إن...","Bi-ikhtiṣār, yaqūl al-khabar inna...","In short, the report says that..."]]}),
  extra({id:"b2-problem-solving",title:"Problems & Solutions",arabicTitle:"المشكلات والحلول",cefr:"B2",unit:"Ideas & society",skill:"Speaking",icon:"🧩",category:"Ideas & society",description:"Describe a problem, compare options, and propose a practical solution.",words:[["مشكلة","Mushkila","Problem"],["حل","Ḥall","Solution"],["سبب","Sabab","Cause / reason"],["نتيجة","Natīja","Result"],["خيار","Khayār","Option"],["اقتراح","Iqti­rāḥ","Suggestion"]],phrases:[["المشكلة هي...","Al-mushkila hiya...","The problem is..."],["أقترح أن...","Aqtar iḥu an...","I suggest that..."],["الحل الأفضل هو...","Al-ḥall al-afḍal huwa...","The best solution is..."]]}),
  extra({id:"b2-professional",title:"Professional Communication",arabicTitle:"التواصل المهني",cefr:"B2",unit:"Study & work",skill:"Writing",icon:"📧",category:"Study & work",description:"Use clearer Arabic for requests, follow-ups, meetings, and workplace communication.",words:[["طلب","Ṭalab","Request"],["مرفق","Murfaq","Attachment"],["موعد نهائي","Mawʿid nihāʾī","Deadline"],["تأكيد","Taʾkīd","Confirmation"],["مناقشة","Munāqasha","Discussion"],["تحديث","Taḥdīth","Update"]],phrases:[["أرسل إليك المرفق","Arsil ilayka al-murfaq","I am sending you the attachment"],["أرجو تأكيد الموعد","Arjū taʾkīd al-mawʿid","Please confirm the appointment"],["سأرسل تحديثاً قريباً","Sa-ursil taḥdīthan qarīban","I will send an update soon"]]}),
  extra({id:"b2-education",title:"Learning & Arguments",arabicTitle:"التعلم وبناء الحجة",cefr:"B2",unit:"Ideas & society",skill:"Speaking",icon:"🎓",category:"Study & work",description:"Explain a position, support it with reasons, and respond to another view.",words:[["فكرة","Fikra","Idea"],["دليل","Dalīl","Evidence"],["حجة","Ḥujja","Argument"],["مقارنة","Muqārana","Comparison"],["نتيجة","Natīja","Conclusion"],["تجربة","Tajriba","Experience"]],phrases:[["من وجهة نظري","Min wijhat naẓarī","From my point of view"],["الدليل على ذلك...","Ad-dalīl ʿalā dhālik...","Evidence for that is..."],["في المقابل...","Fī al-muqābil...","By contrast..."]]}),
  extra({id:"c1-formal-arabic",title:"Formal & Standard Arabic",arabicTitle:"العربية الفصحى الرسمية",cefr:"C1",unit:"Advanced expression",skill:"Register",icon:"📚",category:"Advanced",description:"Shift from casual phrasing to precise Standard Arabic suitable for formal contexts.",words:[["إضافة إلى ذلك","Iḍāfatan ilā dhālik","In addition"],["وفقاً","Wifqan","According to"],["يُرجى","Yurjā","Please / it is requested"],["يتطلب","Yataṭallab","Requires"],["ينبغي","Yanbaghī","Should / ought to"],["بناءً على","Bināʾan ʿalā","Based on"]],phrases:[["يُرجى العلم بأن...","Yurjā al-ʿilm bi-anna...","Please note that..."],["بناءً على المعطيات...","Bināʾan ʿalā al-muʿṭayāt...","Based on the available data..."],["ينبغي النظر في...","Yanbaghī an-naẓar fī...","...should be considered"]]}),
  extra({id:"c1-connectors",title:"Nuance & Connectors",arabicTitle:"الفروق الدقيقة وروابط الكلام",cefr:"C1",unit:"Advanced expression",skill:"Writing",icon:"🔗",category:"Advanced",description:"Make longer explanations coherent with precise cause, contrast, and consequence connectors.",words:[["رغم","Raghma","Despite"],["مع ذلك","Maʿa dhālik","Nevertheless"],["بينما","Baynamā","While / whereas"],["لذلك","Lidhālik","Therefore"],["بالتالي","Bi-t-tālī","Consequently"],["خصوصاً","Khuṣūṣan","Especially"]],phrases:[["رغم ذلك، فإن...","Raghma dhālik, fa-inna...","Nevertheless, ..."],["بالتالي يمكن القول إن...","Bi-t-tālī yumkin al-qawl inna...","Consequently, one can say that..."],["خصوصاً عندما...","Khuṣūṣan ʿindamā...","Especially when..."]]}),
  extra({id:"c1-presentations",title:"Presentations & Explanation",arabicTitle:"العروض والشرح المتقدم",cefr:"C1",unit:"Professional Arabic",skill:"Speaking",icon:"🎤",category:"Advanced",description:"Structure a presentation, highlight key points, and explain implications clearly.",words:[["مقدمة","Muqaddima","Introduction"],["محور","Miḥwar","Theme / axis"],["نقطة","Nuqṭa","Point"],["نتائج","Natāʾij","Findings"],["استنتاج","Istintāj","Inference"],["توصية","Tawṣiya","Recommendation"]],phrases:[["سأبدأ بالنقطة الأولى","Sa-abdaʾ bi-n-nuqṭa al-ūlā","I will start with the first point"],["النتيجة الأهم هي...","An-natīja al-ahamm hiya...","The most important finding is..."],["وبناءً عليه أوصي بـ...","Wa-bināʾan ʿalayhi ūṣī bi...","Accordingly, I recommend..."]]}),
  extra({id:"c1-abstract-discussion",title:"Abstract Discussion",arabicTitle:"النقاش في الموضوعات المجردة",cefr:"C1",unit:"Ideas & society",skill:"Conversation",icon:"💡",category:"Advanced",description:"Discuss abstract ideas such as identity, responsibility, change, and values.",words:[["هوية","Huwiyya","Identity"],["مسؤولية","Masʾūliyya","Responsibility"],["قيمة","Qīma","Value"],["تغيير","Taghyīr","Change"],["مبدأ","Mabdaʾ","Principle"],["توازن","Tawāzun","Balance"]],phrases:[["من حيث المبدأ","Min ḥaythu al-mabdaʾ","In principle"],["يرتبط هذا بـ...","Yartabiṭ hādhā bi...","This is connected to..."],["المسألة أكثر تعقيداً مما تبدو","Al-masʾala akthar taʿqīdan mimmā tabdū","The issue is more complex than it appears"]]}),
  extra({id:"c2-register-style",title:"Register & Style",arabicTitle:"الأسلوب ومستويات اللغة",cefr:"C2",unit:"Mastery",skill:"Register",icon:"🎨",category:"Mastery",description:"Choose wording deliberately for formal, neutral, conversational, and rhetorical contexts.",words:[["صياغة","Ṣiyāgha","Wording / formulation"],["نبرة","Nabra","Tone"],["سياق","Siyāq","Context"],["أسلوب","Uslūb","Style"],["دلالة","Dalāla","Connotation"],["تعبير","Taʿbīr","Expression"]],phrases:[["بحسب السياق، يمكن صياغتها بـ...","Bi-ḥasabi as-siyāq, yumkin ṣiyāghatuhā bi...","Depending on context, it can be phrased as..."],["التعبير هنا أكثر رسمية","At-taʿbīr hunā akthar rasmiyya","The expression here is more formal"],["يحمل هذا التعبير دلالة إضافية","Yaḥmil hādhā at-taʿbīr dalāla iḍāfiyya","This expression carries an additional connotation"]]}),
  extra({id:"c2-rhetoric",title:"Rhetoric & Persuasion",arabicTitle:"البلاغة والإقناع",cefr:"C2",unit:"Mastery",skill:"Speaking",icon:"⚖️",category:"Mastery",description:"Persuade, qualify claims, anticipate objections, and make sophisticated comparisons.",words:[["إقناع","Iq­nāʿ","Persuasion"],["اعتراض","Iʿtirāḍ","Objection"],["افتراض","Iftirāḍ","Assumption"],["مفارقة","Mufāraqa","Paradox"],["مقنع","Muqniʿ","Convincing"],["موضوعي","Mawḍūʿī","Objective"]],phrases:[["قد يُعترض على ذلك بأن...","Qad yuʿtaraḍ ʿalā dhālik bi-anna...","It may be objected that..."],["مع التسليم بأن...","Maʿa at-taslīm bi-anna...","While acknowledging that..."],["الأكثر إقناعاً في هذه الحالة...","Al-akthar iqnāʿan fī hādhihi al-ḥāla...","The most persuasive point here..."]]}),
  extra({id:"c2-idiomatic-nuance",title:"Idioms & Nuance",arabicTitle:"التعابير والفروق الدقيقة",cefr:"C2",unit:"Mastery",skill:"Listening",icon:"🧠",category:"Mastery",description:"Interpret implied meaning, idiomatic phrasing, and subtle differences in tone.",words:[["ضمنياً","Ḍimniyyan","Implicitly"],["حرفياً","Ḥarfiyyan","Literally"],["مجازاً","Majāzan","Figuratively"],["سخرية","Sukhriyya","Irony / sarcasm"],["تلميح","Talmīḥ","Hint / allusion"],["مبالغة","Mubālagha","Exaggeration"]],phrases:[["ليس المقصود حرفياً","Laysa al-maqṣūd ḥarfiyyan","It is not meant literally"],["في هذا السياق، يُفهم ضمنياً أن...","Fī hādhā as-siyāq, yufham ḍimniyyan anna...","In this context, it is implied that..."],["هذا التعبير يحمل قدراً من السخرية","Hādhā at-taʿbīr yaḥmil qadran min as-sukhriyya","This expression carries some irony"]]}),
  extra({id:"c2-critical-reading",title:"Critical Reading",arabicTitle:"القراءة النقدية",cefr:"C2",unit:"Mastery",skill:"Reading",icon:"🔎",category:"Mastery",description:"Evaluate claims, distinguish evidence from opinion, and track an author's assumptions.",words:[["ادعاء","Iddiʿāʾ","Claim"],["برهان","Burhān","Proof"],["مصدرية","Maṣdariyya","Source reliability"],["تحيز","Taḥayyuz","Bias"],["افتراض","Iftirāḍ","Assumption"],["استدلال","Istidlāl","Inference / reasoning"]],phrases:[["يستند هذا الادعاء إلى...","Yastanid hādhā al-iddiʿāʾ ilā...","This claim is based on..."],["لا يكفي ذلك دليلاً على...","Lā yakfī dhālik dalīlan ʿalā...","That is not sufficient evidence for..."],["ينبغي التمييز بين الرأي والحقيقة","Yanbaghī at-tamyīz bayna ar-raʾy wa al-ḥaqīqa","One should distinguish opinion from fact"]]}),
];

export const curriculumLessons: CurriculumLesson[] = [...core, ...supplementalLessons].map((lesson,index)=>({...lesson,order:index+1}));

export function getCurriculumLesson(id:string){return curriculumLessons.find(l=>l.id===id);}
export function lessonsForLevel(level:CEFR){return curriculumLessons.filter(l=>l.cefr===level);}
export const curriculumTotalVocab=curriculumLessons.reduce((sum,l)=>sum+l.vocabulary.length,0);
export const curriculumTotalPhrases=curriculumLessons.reduce((sum,l)=>sum+l.phrases.length,0);
export const curriculumCategories=Array.from(new Set(curriculumLessons.map(l=>l.category)));
export const totalCurriculumLessons=curriculumLessons.length;
