export type CardState={box:number;interval:number;due:number;reps:number;lapses:number;ease:number;correct:number;seen:number};
export type LessonState={completed:boolean;bestScore:number;xp:number;lastStudied:number;cards:Record<string,CardState>};
export type ProgressState={version:2;xp:number;streak:number;lastActive:string|null;lessons:Record<string,LessonState>};
const KEY="alifya:progress:v2";
const empty=():ProgressState=>({version:2,xp:0,streak:0,lastActive:null,lessons:{}});
export function loadProgress():ProgressState{if(typeof window==="undefined")return empty();try{const raw=window.localStorage.getItem(KEY);if(!raw)return empty();const parsed=JSON.parse(raw);if(parsed?.version!==2)return empty();return parsed as ProgressState;}catch{return empty();}}
function save(state:ProgressState){window.localStorage.setItem(KEY,JSON.stringify(state));window.dispatchEvent(new Event("alifya:progress-updated"));return state;}
function today(){return new Date().toISOString().slice(0,10)}
function dayDiff(a:string,b:string){return Math.round((new Date(b).getTime()-new Date(a).getTime())/86400000)}
function touch(state:ProgressState){const t=today(); if(state.lastActive!==t){if(state.lastActive&&dayDiff(state.lastActive,t)===1)state.streak+=1;else if(state.lastActive!==t)state.streak=1;state.lastActive=t;} return state;}
export function recordLessonResult(lessonId:string,score:number,total:number):ProgressState{const s=loadProgress();touch(s);const pct=total?Math.round(score/total*100):0;const old=s.lessons[lessonId]??{completed:false,bestScore:0,xp:0,lastStudied:0,cards:{}};const gain=Math.max(10,score*8)+(pct>=80?15:0);s.lessons[lessonId]={...old,completed:true,bestScore:Math.max(old.bestScore,pct),xp:Math.max(old.xp,gain),lastStudied:Date.now()};s.xp+=gain;return save(s);}
export function reviewCard(lessonId:string,cardId:string,rating:"again"|"hard"|"good"|"easy",correct:boolean):ProgressState{const s=loadProgress();touch(s);const lesson=s.lessons[lessonId]??{completed:false,bestScore:0,xp:0,lastStudied:0,cards:{}};const old=lesson.cards[cardId]??{box:0,interval:0,due:0,reps:0,lapses:0,ease:2.5,correct:0,seen:0};let interval=old.interval;let box=old.box;let ease=old.ease;
 if(rating==="again"){box=0;interval=0;ease=Math.max(1.3,ease-0.2);} else {box=Math.min(5,box+1);const mult=rating==="easy"?2.2:rating==="hard"?1.2:1.7;interval=Math.max(1,Math.round((old.interval||1)*mult*ease/2.5));if(rating==="easy")ease=Math.min(3.0,ease+0.15);if(rating==="hard")ease=Math.max(1.3,ease-0.15);}
 lesson.cards={...lesson.cards,[cardId]:{box,interval,due:Date.now()+interval*86400000,reps:old.reps+1,lapses:old.lapses+(rating==="again"?1:0),ease,correct:old.correct+(correct?1:0),seen:old.seen+1}};lesson.lastStudied=Date.now();s.lessons[lessonId]=lesson;s.xp+=rating==="easy"?6:rating==="good"?4:rating==="hard"?2:1;return save(s);}
export function stats(s:ProgressState,totalLessons:number){const completed=Object.values(s.lessons).filter(x=>x.completed).length;const scores=Object.values(s.lessons).filter(x=>x.completed).map(x=>x.bestScore);return{completed,total:totalLessons,pct:totalLessons?Math.round(completed/totalLessons*100):0,avgScore:scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0,xp:s.xp,streak:s.streak};}
export function dueCards(s:ProgressState,lessonId:string){const cards=s.lessons[lessonId]?.cards??{};return Object.entries(cards).filter(([,v])=>v.due<=Date.now()).map(([id])=>id)}
export function resetProgress(){window.localStorage.removeItem(KEY);window.dispatchEvent(new Event("alifya:progress-updated"));}
